version: "3"
services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=portishead
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  portishead:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    entrypoint:
      - tini
      - -v
    command:
      - ./migrate-then-start.sh
    environment:
      - PORT=4000
      - DB_USER=postgres
      - DB_PWD=postgres
      - DB_HOST=postgres
      # - DB_HOST=host.docker.internal
      - SECRET_KEY_BASE=mysecret
