version: "3.3"
services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=portishead
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  traefik:
    image: traefik
    command:
      - --entrypoints.web.address=:80
      - --providers.docker
      - --api.insecure
      # - --log.level=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=Host(`traefik.docker.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"

  portishead:
    build: .
    depends_on:
      - postgres
    entrypoint:
      - tini
      - -v
    command:
      - ./migrate-then-start.sh
    environment:
      - PORT=8181
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      # - DB_HOST=host.docker.internal
      - SECRET_KEY_BASE=mysecret
    labels:
      - "traefik.http.routers.portishead.rule=Host(`portishead.docker.localhost`)"
      - "traefik.http.services.portishead.loadbalancer.server.port=8181"
# http://portishead.docker.localhost/
# Dashboard [api@internal] http://traefik.docker.localhost/
